package ai

import (
	"context"
	"fmt"

	"github.com/RDX463/github-work-summary/internal/summary"
	"google.golang.org/genai"
)

// GeminiProvider implements the Provider interface using Google's GenAI SDK.
type GeminiProvider struct {
	client *genai.Client
	model  string
}

// NewGeminiProvider creates a new Gemini-backed AI provider.
func NewGeminiProvider(ctx context.Context, apiKey string) (*GeminiProvider, error) {
	client, err := genai.NewClient(ctx, &genai.ClientConfig{
		APIKey:  apiKey,
		Backend: genai.BackendGeminiAPI,
	})
	if err != nil {
		return nil, err
	}
	return &GeminiProvider{
		client: client,
		model:  "gemini-2.0-flash", // High performance stable model
	}, nil
}

// Summarize generates a summary using Gemini.
func (p *GeminiProvider) Summarize(ctx context.Context, report summary.Report) (string, error) {
	prompt := BuildReportPrompt(report)
	
	result, err := p.client.Models.GenerateContent(
		ctx,
		p.model,
		[]*genai.Content{{Parts: []*genai.Part{{Text: prompt}}}},
		nil,
	)
	if err != nil {
		return "", fmt.Errorf("gemini generation failed: %w", err)
	}

	if len(result.Candidates) == 0 || len(result.Candidates[0].Content.Parts) == 0 {
		return "", fmt.Errorf("no summary generated by gemini")
	}

	return result.Candidates[0].Content.Parts[0].Text, nil
}

// Name returns the provider name.
func (p *GeminiProvider) Name() string {
	return "gemini"
}
