package ai

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/RDX463/github-work-summary/internal/summary"
)

const (
	ollamaURL = "http://localhost:11434/api/generate"
)

// OllamaProvider implements the Provider interface for local LLM usage via Ollama.
type OllamaProvider struct {
	model string
}

type ollamaRequest struct {
	Model     string `json:"model"`
	Prompt    string `json:"prompt"`
	Stream    bool   `json:"stream"`
	Raw       bool   `json:"raw"`
}

type ollamaResponse struct {
	Response string `json:"response"`
	Error    string `json:"error"`
}

// NewOllamaProvider creates a new local Ollama provider.
func NewOllamaProvider() *OllamaProvider {
	return &OllamaProvider{
		model: "llama3", // Standard capable local model
	}
}

// Summarize generates a summary via local Ollama.
func (p *OllamaProvider) Summarize(ctx context.Context, report summary.Report) (string, error) {
	prompt := BuildReportPrompt(report)

	reqBody := ollamaRequest{
		Model:  p.model,
		Prompt: prompt,
		Stream: false,
		Raw:    false,
	}

	jsonData, err := json.Marshal(reqBody)
	if err != nil {
		return "", err
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodPost, ollamaURL, bytes.NewBuffer(jsonData))
	if err != nil {
		return "", err
	}

	req.Header.Set("Content-Type", "application/json")

	// Adjusting timeout for local generation (can be slow depending on hardware)
	client := &http.Client{Timeout: 90 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return "", fmt.Errorf("ollama request failed (is it running?): %w", err)
	}
	defer resp.Body.Close()

	var result ollamaResponse
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return "", err
	}

	if result.Error != "" {
		return "", fmt.Errorf("ollama error: %s", result.Error)
	}

	if result.Response == "" {
		return "", fmt.Errorf("no summary generated by ollama")
	}

	return result.Response, nil
}

// Name returns the provider name.
func (p *OllamaProvider) Name() string {
	return "ollama"
}
